package uk.ac.uea.mathsthing;

/**
 *  Class to represent the tokens generated by the lexer
 *  Mostly for use by the parser
 * @author Laura Goold
 *
 */
public class Token {

	public final TokenType type; //type of token e.g operand
	public final String val;
	public final boolean urany; //is token a uranary operator
	
	/**
	 * Constructor for token, uranary is false by default
	 * @param val actual value of this token
	 * @param type type of token
	 */
	public Token(String val, TokenType type)
	{
		this.type = type;
		this.val = val;
		this.urany = false;
	}
	
	/**
	 * Conrtuctor for token allowing user to set if uranary
	 * @param val actual value of token
	 * @param type type of token
	 * @param urany if uranary or not
	 */
	public Token(String val, TokenType type, boolean urany)
	{
		this.type = type;
		this.val = val;
		this.urany = urany;
	}
	
	/**
	 * Accesor to return the value of this token
	 * @return String representation of the token's value 
	 */
	public String getToken() { return this.val; }
	
	/**
	 * String just contains the value of the token
	 */
	@Override
	public String toString() { return this.val; }
}
