/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_uea_mathsthing_NativeParser */

#ifndef _Included_uk_ac_uea_mathsthing_NativeParser
#define _Included_uk_ac_uea_mathsthing_NativeParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_uea_mathsthing_NativeParser
 * Method:    setFormulaNative
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_uea_mathsthing_NativeParser_setFormulaNative
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     uk_ac_uea_mathsthing_NativeParser
 * Method:    getResultNative
 * Signature: (Ljava/util/HashMap;)D
 */
JNIEXPORT jdouble JNICALL Java_uk_ac_uea_mathsthing_NativeParser_getResultNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     uk_ac_uea_mathsthing_NativeParser
 * Method:    getFirstDerivativeNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_uk_ac_uea_mathsthing_NativeParser_getFirstDerivativeNative
  (JNIEnv *, jobject);

/*
 * Class:     uk_ac_uea_mathsthing_NativeParser
 * Method:    getSecondDerivativeNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_uk_ac_uea_mathsthing_NativeParser_getSecondDerivativeNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
